<?xml version="1.0" encoding="utf-8"?><Database Name="CoinMaster" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=173.249.0.88;Initial Catalog=CoinMaster;User ID=iChol" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CoinMasterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.wallet" Member="wallets">
    <Type Name="wallet">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Coinwallet" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Refer11" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>